### PR TITLE
Doesn't Return Rent Zestimate

### PR DESCRIPTION
**Pull request by danielberkompas**
Zillow's [api docs for GetZestimate](http://www.zillow.com/howto/api/GetZestimate.htm) indicate that you can get a RentZestimate by passing the `rentzestimate: true` option.

Rubillow works with this up to a point.  When I added `rentzestimate: true` to the options in `HomeValuation#zestimate` like so...

``` ruby
Rubillow::HomeValuation.zestimate(zpid: zillow_property_id, rentzestimate: true)
```

...Zillow **did** respond with the RentZestimate.  I can see it in the `@parser` variable of the resulting class.  However, it didn't assign the values to a property that I can easily access.  

Any chance this could be fixed?  I'm willing to take a stab at it myself and open a pull request.

### CODE REVIEW

**Comment by synewaves** [comment]
This is definitely something that needs to be added.  I'll check into it and see what can be done.

**Comment by danielberkompas** [comment]
@synewaves I have a pull request in the works, will be posting it shortly.

**Comment by danielberkompas** [comment]
@synewaves Any idea what is breaking the build on TravisCI?  I can't really figure it out.  Specs work fine on my local machine in 1.9.3, so not sure why it fails for 1.9.3 in TravisCI.

**Comment by synewaves** [comment]
I'm getting an error running specs on my end, but it's unrelated to these commits.  I'm getting an error with the RSpec custom matcher (failure_message is undefined).  I can fix that error in the test and everything runs fine.  I am going to commit this change in master.  We'll see if that fixes the Travis build.

**Comment by synewaves** [comment]
@danielberkompas my current master passes on all versions in Travis now.

**Comment by danielberkompas** [comment]
@synewaves My changes are now passing.  Any thoughts?

**Comment by synewaves** [comment]
Looks good.  I'll pull this in.

**Pull request merged**
